ARG BASE_IMAGE
FROM $BASE_IMAGE

# Install magic_enum from source (workaround for broken apt package)
RUN cd /tmp && \
    git clone https://github.com/Neargye/magic_enum.git && \
    mkdir -p magic_enum/build && cd magic_enum/build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DMAGIC_ENUM_OPT_BUILD_EXAMPLES=OFF -DMAGIC_ENUM_OPT_BUILD_TESTS=OFF && \
    cmake --install . && \
    cp /usr/include/magic_enum/magic_enum.hpp /usr/include/magic_enum.hpp && \
    cd / && rm -rf /tmp/magic_enum

# Install Isaac ROS visual_slam runtime dependencies
RUN apt-get update && apt-get install -y \
    ros-humble-isaac-ros-common \
    ros-humble-isaac-ros-gxf \
    ros-humble-gxf-isaac-gems \
    ros-humble-gxf-isaac-atlas \
    ros-humble-gxf-isaac-gxf-helpers \
    ros-humble-gxf-isaac-image-flip \
    ros-humble-gxf-isaac-message-compositor \
    ros-humble-gxf-isaac-messages \
    ros-humble-gxf-isaac-optimizer \
    ros-humble-gxf-isaac-sight \
    ros-humble-gxf-isaac-tensorops \
    ros-humble-isaac-ros-nitros \
    ros-humble-isaac-ros-tensor-list-interfaces \
    ros-humble-isaac-ros-nitros-tensor-list-type \
    ros-humble-isaac-ros-managed-nitros \
    ros-humble-isaac-ros-nitros-camera-info-type \
    ros-humble-isaac-ros-nitros-image-type \
    ros-humble-isaac-ros-image-proc \
    && rm -rf /var/lib/apt/lists/*
